#define VTRAITS_MATHERSHIP list( \
	ZTRAIT_SUN_TYPE = STATIC_EXPOSED,\
	ZTRAIT_STATION = TRUE, \
	ZTRAIT_BOMBCAP_MULTIPLIER = 2)

#define SHIP_FLAG_MATHERSHIP (1 << 0)
#define SHIP_FLAG_DOCKABLE (2 << 0)
#define SHIP_FLAG_LANDABLE (3 << 0)
#define SHIP_FLAG_MOVEABLE (4 << 0)
