arrowParens: always
endOfLine: lf
#Deprecated
# jsxBracketSameLine: true
bracketSameLine: false
jsxSingleQuote: false
printWidth: 80
proseWrap: preserve
quoteProps: preserve
semi: true
singleQuote: true
tabWidth: 2
trailingComma: es5
useTabs: false
# PrettierX config, currently unused
# importFormatting: oneline
# offsetTernaryExpressions: true
# breakLongMethodChains: true
